"""Reczny multi-plik: tabela document_file na strony 2+ dokumentu

Revision ID: 177e171d0f37
Revises: 8d6d6a7313c9
Create Date: 2026-08-04 03:43:23.107671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '177e171d0f37'
down_revision: Union[str, None] = '8d6d6a7313c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_file',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('file_key', sa.String(), nullable=False),
    sa.Column('mime', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_file_document_id'), 'document_file', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_file_document_id'), table_name='document_file')
    op.drop_table('document_file')
    # ### end Alembic commands ###
