"""Etap 3: model special_rule

Revision ID: e14bd64f173f
Revises: fdafa7346dc0
Create Date: 2026-07-27 19:19:08.893528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e14bd64f173f'
down_revision: Union[str, None] = 'fdafa7346dc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('special_rule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('pattern', sa.String(), nullable=False),
    sa.Column('target_kod', sa.String(), nullable=True),
    sa.Column('kod_template', sa.String(), nullable=True),
    sa.Column('value_regex', sa.String(), nullable=True),
    sa.Column('rounding_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_value', sa.Float(), nullable=True),
    sa.Column('normalize', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('special_rule')
    # ### end Alembic commands ###
