"""Etap 7: modele Document, DocumentItem

Revision ID: 9de150ab780e
Revises: 099794a318bb
Create Date: 2026-07-27 20:10:18.342780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de150ab780e'
down_revision: Union[str, None] = '099794a318bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('numer_projektu', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('magazyn', sa.String(), nullable=True),
    sa.Column('file_key', sa.String(), nullable=False),
    sa.Column('mime', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('used_provider', sa.String(), nullable=True),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_user_id'), 'document', ['user_id'], unique=False)
    op.create_table('document_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('rozpoznana_nazwa', sa.String(), nullable=False),
    sa.Column('matched_product_id', sa.UUID(), nullable=True),
    sa.Column('match_kod', sa.String(), nullable=True),
    sa.Column('match_nazwa', sa.String(), nullable=True),
    sa.Column('match_jm', sa.String(), nullable=True),
    sa.Column('ilosc_wydana', sa.Float(), nullable=True),
    sa.Column('ilosc_zuzyta', sa.Float(), nullable=True),
    sa.Column('ilosc_finalna', sa.Float(), nullable=True),
    sa.Column('match_quality', sa.String(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('off_form', sa.Boolean(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('form_note', sa.String(), nullable=False),
    sa.Column('uwagi', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['matched_product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_item_document_id'), 'document_item', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_item_document_id'), table_name='document_item')
    op.drop_table('document_item')
    op.drop_index(op.f('ix_document_user_id'), table_name='document')
    op.drop_table('document')
    # ### end Alembic commands ###
