"""Etap 2: modele Product, ProductAlias, WarehouseVariant

Revision ID: fdafa7346dc0
Revises: 
Create Date: 2026-07-27 19:04:11.876685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdafa7346dc0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kod', sa.String(), nullable=False),
    sa.Column('nazwa', sa.String(), nullable=False),
    sa.Column('jm', sa.String(), nullable=False),
    sa.Column('grupa', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('atrybuty', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('kolor_domniemany', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_kod'), 'product', ['kod'], unique=True)
    op.create_table('product_alias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('alias_text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_alias_product_id'), 'product_alias', ['product_id'], unique=False)
    op.create_table('warehouse_variant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('magazyn', sa.String(), nullable=False),
    sa.Column('kod_docelowy', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_variant_product_id'), 'warehouse_variant', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouse_variant_product_id'), table_name='warehouse_variant')
    op.drop_table('warehouse_variant')
    op.drop_index(op.f('ix_product_alias_product_id'), table_name='product_alias')
    op.drop_table('product_alias')
    op.drop_index(op.f('ix_product_kod'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
